import type { SceneCategory, SceneTemplate } from "@/types/scene-types";

const byCategoryAccent: Record<SceneCategory, string> = {
  IPL: "from-fuchsia-500/30 via-primary/20 to-orange-400/20",
  International: "from-sky-500/30 via-primary/20 to-blue-900/20",
  "Test Cricket": "from-slate-200/25 via-primary/15 to-emerald-900/20",
  ODI: "from-blue-500/25 via-primary/15 to-cyan-500/20",
  T20: "from-violet-500/30 via-primary/20 to-pink-500/20",
  Training: "from-lime-500/25 via-primary/20 to-stone-600/20",
};

type TemplateInput = Omit<SceneTemplate, "thumbnail"> & { icon?: string };

function scene(input: TemplateInput): SceneTemplate {
  return {
    ...input,
    thumbnail: {
      accent: byCategoryAccent[input.category],
      icon: input.icon ?? "🏏",
    },
  };
}

const scenes: SceneTemplate[] = [
  // IPL
  scene({ id: "ipl-final-trophy-lift", sceneName: "IPL Final Trophy Lift", description: "A premium floodlit final celebration with trophy, confetti and packed stadium energy.", category: "IPL", difficulty: "Pro", popularity: "Trending", recommendedFor: ["Captain", "All-rounder"], tags: ["IPL", "Celebration", "Hero", "Poster", "Night Match"], recommendedCamera: "Telephoto Lens", recommendedLighting: "Floodlights", recommendedStadium: "M Chinnaswamy Stadium", recommendedPose: "Trophy Lift", recommendedJersey: "RCB", recommendedFormat: "IPL", recommendedPromptPreset: "Victory Celebration", recommendedQualityProfile: "Ultra", recommendedCreativeStrategy: "IPL Promotional", icon: "🏆" }),
  scene({ id: "ipl-player-introduction", sceneName: "Player Introduction", description: "Hero player reveal with franchise lights, smoke, jersey detail and dramatic entry framing.", category: "IPL", difficulty: "Intermediate", popularity: "Popular", recommendedFor: ["Batsman", "Captain"], tags: ["IPL", "Hero", "Portrait", "Poster"], recommendedCamera: "Close-up Portrait", recommendedLighting: "Floodlights", recommendedStadium: "Wankhede Stadium", recommendedPose: "Walking into Stadium", recommendedJersey: "MI", recommendedFormat: "IPL", recommendedPromptPreset: "Epic IPL", recommendedQualityProfile: "High", recommendedCreativeStrategy: "Player Portrait", icon: "✨" }),
  scene({ id: "ipl-captain-walk", sceneName: "Captain Walk", description: "Confident captain walking through stadium entrance before a high-pressure IPL match.", category: "IPL", difficulty: "Intermediate", popularity: "Popular", recommendedFor: ["Captain"], tags: ["IPL", "Captain", "Hero"], recommendedCamera: "Ground Level", recommendedLighting: "Golden Hour", recommendedStadium: "Eden Gardens", recommendedPose: "Walking into Stadium", recommendedJersey: "KKR", recommendedFormat: "IPL", recommendedPromptPreset: "Legendary Captain", recommendedQualityProfile: "High", recommendedCreativeStrategy: "Stadium Entrance", icon: "🚶" }),
  scene({ id: "ipl-winning-celebration", sceneName: "Winning Celebration", description: "Emotional IPL win moment with raised arms, crowd, teammates and dramatic lights.", category: "IPL", difficulty: "Advanced", popularity: "Trending", recommendedFor: ["Batsman", "All-rounder", "Captain"], tags: ["IPL", "Celebration", "Action", "Night Match"], recommendedCamera: "Action Camera", recommendedLighting: "Floodlights", recommendedStadium: "Narendra Modi Stadium", recommendedPose: "Celebration", recommendedJersey: "GT", recommendedFormat: "IPL", recommendedPromptPreset: "Victory Celebration", recommendedQualityProfile: "Ultra", recommendedCreativeStrategy: "Victory Celebration", icon: "🎉" }),
  scene({ id: "ipl-batting-hero-shot", sceneName: "Batting Hero Shot", description: "Signature batting portrait in full franchise kit with stadium bokeh and heroic stance.", category: "IPL", difficulty: "Easy", popularity: "Popular", recommendedFor: ["Batsman", "Captain"], tags: ["IPL", "Batsman", "Hero", "Portrait"], recommendedCamera: "Telephoto Lens", recommendedLighting: "Night Match", recommendedStadium: "M Chinnaswamy Stadium", recommendedPose: "Cover Drive", recommendedJersey: "RCB", recommendedFormat: "IPL", recommendedPromptPreset: "Match Winner", recommendedQualityProfile: "High", recommendedCreativeStrategy: "Sports Magazine", icon: "🏏" }),
  scene({ id: "ipl-bowling-action", sceneName: "Bowling Action", description: "Explosive IPL bowling follow-through with motion energy and realistic pitch contact.", category: "IPL", difficulty: "Advanced", popularity: "Rising", recommendedFor: ["Bowler", "All-rounder"], tags: ["IPL", "Bowler", "Action"], recommendedCamera: "Action Camera", recommendedLighting: "Floodlights", recommendedStadium: "Wankhede Stadium", recommendedPose: "Fast Bowling", recommendedJersey: "MI", recommendedFormat: "IPL", recommendedPromptPreset: "Epic IPL", recommendedQualityProfile: "High", recommendedCreativeStrategy: "Sports Broadcast", icon: "⚡" }),
  scene({ id: "ipl-boundary-celebration", sceneName: "Boundary Celebration", description: "Boundary-line celebration after a spectacular catch or four-saving effort.", category: "IPL", difficulty: "Advanced", popularity: "Rising", recommendedFor: ["All-rounder", "Batsman"], tags: ["IPL", "Action", "Celebration"], recommendedCamera: "Wide Stadium", recommendedLighting: "Floodlights", recommendedStadium: "Eden Gardens", recommendedPose: "Celebration", recommendedJersey: "KKR", recommendedFormat: "IPL", recommendedPromptPreset: "Victory Celebration", recommendedQualityProfile: "High", recommendedCreativeStrategy: "Sports Broadcast", icon: "🙌" }),
  scene({ id: "ipl-crowd-interaction", sceneName: "Crowd Interaction", description: "Player saluting an electric IPL crowd with franchise colors and stadium spectacle.", category: "IPL", difficulty: "Intermediate", popularity: "Popular", recommendedFor: ["Captain", "Batsman"], tags: ["IPL", "Celebration", "Hero"], recommendedCamera: "Wide Stadium", recommendedLighting: "Night Match", recommendedStadium: "Narendra Modi Stadium", recommendedPose: "Celebration", recommendedJersey: "CSK", recommendedFormat: "IPL", recommendedPromptPreset: "Epic IPL", recommendedQualityProfile: "High", recommendedCreativeStrategy: "IPL Promotional", icon: "📣" }),
  scene({ id: "ipl-training-nets", sceneName: "Training Nets", description: "Professional IPL training nets with focused athlete, coaches and practice equipment.", category: "IPL", difficulty: "Easy", popularity: "Classic", recommendedFor: ["Batsman", "Bowler", "Coach"], tags: ["IPL", "Training", "Batsman", "Bowler"], recommendedCamera: "Ground Level", recommendedLighting: "Afternoon", recommendedStadium: "M Chinnaswamy Stadium", recommendedPose: "Practice Nets", recommendedJersey: "RCB", recommendedFormat: "IPL", recommendedPromptPreset: "Training Session", recommendedQualityProfile: "Standard", recommendedCreativeStrategy: "Net Practice", icon: "🥅" }),
  scene({ id: "ipl-match-warm-up", sceneName: "Match Warm-up", description: "Pre-match stretching and warm-up scene with professional kit and stadium anticipation.", category: "IPL", difficulty: "Easy", popularity: "Classic", recommendedFor: ["All-rounder", "Coach"], tags: ["IPL", "Training", "Day Match"], recommendedCamera: "Broadcast Camera", recommendedLighting: "Golden Hour", recommendedStadium: "Wankhede Stadium", recommendedPose: "Practice Nets", recommendedJersey: "MI", recommendedFormat: "IPL", recommendedPromptPreset: "Training Session", recommendedQualityProfile: "Standard", recommendedCreativeStrategy: "Training Session", icon: "🔥" }),

  // International
  scene({ id: "world-cup-final", sceneName: "World Cup Final", description: "Global tournament final hero image with national colors, stadium scale and trophy-era drama.", category: "International", difficulty: "Pro", popularity: "Trending", recommendedFor: ["Captain", "Batsman", "All-rounder"], tags: ["World Cup", "Hero", "Poster", "Celebration"], recommendedCamera: "Telephoto Lens", recommendedLighting: "Floodlights", recommendedStadium: "Melbourne Cricket Ground", recommendedPose: "Trophy Lift", recommendedJersey: "India", recommendedFormat: "World Cup", recommendedPromptPreset: "World Cup Hero", recommendedQualityProfile: "Ultra", recommendedCreativeStrategy: "ICC Promotional", icon: "🌍" }),
  scene({ id: "national-anthem", sceneName: "National Anthem", description: "Respectful anthem-line portrait with national kit, stadium lights and emotional focus.", category: "International", difficulty: "Intermediate", popularity: "Classic", recommendedFor: ["Captain", "Batsman", "Bowler"], tags: ["World Cup", "Portrait", "Captain"], recommendedCamera: "Close-up Portrait", recommendedLighting: "Morning", recommendedStadium: "Lord's", recommendedPose: "Walking into Stadium", recommendedJersey: "India", recommendedFormat: "International", recommendedPromptPreset: "World Cup Hero", recommendedQualityProfile: "High", recommendedCreativeStrategy: "Player Portrait", icon: "🎵" }),
  scene({ id: "international-captain-portrait", sceneName: "Captain Portrait", description: "Clean national captain portrait with serious expression and premium editorial lighting.", category: "International", difficulty: "Easy", popularity: "Popular", recommendedFor: ["Captain"], tags: ["Captain", "Portrait", "Hero"], recommendedCamera: "Close-up Portrait", recommendedLighting: "Golden Hour", recommendedStadium: "The Oval", recommendedPose: "Press Conference", recommendedJersey: "India", recommendedFormat: "International", recommendedPromptPreset: "Legendary Captain", recommendedQualityProfile: "Ultra", recommendedCreativeStrategy: "Sports Magazine", icon: "👑" }),
  scene({ id: "international-match-winning-shot", sceneName: "Match Winning Shot", description: "The decisive shot moment captured with broadcast realism and crowd eruption.", category: "International", difficulty: "Advanced", popularity: "Trending", recommendedFor: ["Batsman", "All-rounder"], tags: ["Action", "Batsman", "Hero"], recommendedCamera: "Broadcast Camera", recommendedLighting: "Floodlights", recommendedStadium: "Melbourne Cricket Ground", recommendedPose: "Straight Drive", recommendedJersey: "India", recommendedFormat: "International", recommendedPromptPreset: "Match Winner", recommendedQualityProfile: "Ultra", recommendedCreativeStrategy: "Sports Broadcast", icon: "💥" }),
  scene({ id: "presentation-ceremony", sceneName: "Presentation Ceremony", description: "Post-match ceremony moment with award, microphones, officials and stadium background.", category: "International", difficulty: "Intermediate", popularity: "Classic", recommendedFor: ["Captain", "Batsman", "Bowler"], tags: ["Celebration", "Portrait"], recommendedCamera: "Telephoto Lens", recommendedLighting: "Night Match", recommendedStadium: "Lord's", recommendedPose: "Holding Trophy", recommendedJersey: "India", recommendedFormat: "International", recommendedPromptPreset: "Victory Celebration", recommendedQualityProfile: "High", recommendedCreativeStrategy: "ICC Promotional", icon: "🎖️" }),
  scene({ id: "player-of-the-match", sceneName: "Player of the Match", description: "Award portrait with confident player holding match award in broadcast presentation style.", category: "International", difficulty: "Easy", popularity: "Popular", recommendedFor: ["Batsman", "Bowler", "All-rounder"], tags: ["Hero", "Portrait"], recommendedCamera: "Close-up Portrait", recommendedLighting: "Floodlights", recommendedStadium: "Eden Gardens", recommendedPose: "Holding Trophy", recommendedJersey: "India", recommendedFormat: "International", recommendedPromptPreset: "Match Winner", recommendedQualityProfile: "High", recommendedCreativeStrategy: "Sports Magazine", icon: "⭐" }),
  scene({ id: "international-press-conference", sceneName: "Press Conference", description: "Realistic post-match media room with microphones, team kit and controlled lighting.", category: "International", difficulty: "Easy", popularity: "Classic", recommendedFor: ["Captain", "Coach"], tags: ["Captain", "Portrait"], recommendedCamera: "Close-up Portrait", recommendedLighting: "Cloudy", recommendedStadium: "Lord's", recommendedPose: "Press Conference", recommendedJersey: "India", recommendedFormat: "International", recommendedPromptPreset: "Press Conference", recommendedQualityProfile: "High", recommendedCreativeStrategy: "Press Conference", icon: "🎙️" }),
  scene({ id: "victory-lap", sceneName: "Victory Lap", description: "Player walking around stadium with flag, crowd applause and late-evening atmosphere.", category: "International", difficulty: "Advanced", popularity: "Popular", recommendedFor: ["Captain", "All-rounder"], tags: ["Celebration", "World Cup", "Hero"], recommendedCamera: "Wide Stadium", recommendedLighting: "Golden Hour", recommendedStadium: "Melbourne Cricket Ground", recommendedPose: "Walking into Stadium", recommendedJersey: "India", recommendedFormat: "World Cup", recommendedPromptPreset: "Victory Celebration", recommendedQualityProfile: "Ultra", recommendedCreativeStrategy: "Victory Celebration", icon: "🏁" }),

  // Test Cricket
  scene({ id: "classic-test-match", sceneName: "Classic Test Match", description: "Traditional whites, green pitch, calm intensity and heritage stadium atmosphere.", category: "Test Cricket", difficulty: "Intermediate", popularity: "Classic", recommendedFor: ["Batsman", "Bowler", "Captain"], tags: ["Day Match", "Hero", "Portrait"], recommendedCamera: "Broadcast Camera", recommendedLighting: "Afternoon", recommendedStadium: "Lord's", recommendedPose: "Straight Drive", recommendedJersey: "India", recommendedFormat: "Test", recommendedPromptPreset: "Legendary Captain", recommendedQualityProfile: "High", recommendedCreativeStrategy: "Sports Documentary", icon: "⚪" }),
  scene({ id: "slip-catch", sceneName: "Slip Catch", description: "Explosive slip cordon catch with whites, red ball and sharp reflex moment.", category: "Test Cricket", difficulty: "Pro", popularity: "Rising", recommendedFor: ["Wicket Keeper", "All-rounder"], tags: ["Action", "Wicket Keeper", "Day Match"], recommendedCamera: "Action Camera", recommendedLighting: "Morning", recommendedStadium: "The Oval", recommendedPose: "Celebration", recommendedJersey: "India", recommendedFormat: "Test", recommendedPromptPreset: "Match Winner", recommendedQualityProfile: "Ultra", recommendedCreativeStrategy: "Sports Documentary", icon: "🧤" }),
  scene({ id: "fast-bowling-spell", sceneName: "Fast Bowling Spell", description: "Test match fast bowler in rhythm with red ball, pitch dust and intense focus.", category: "Test Cricket", difficulty: "Advanced", popularity: "Popular", recommendedFor: ["Bowler"], tags: ["Bowler", "Action", "Day Match"], recommendedCamera: "Telephoto Lens", recommendedLighting: "Afternoon", recommendedStadium: "Lord's", recommendedPose: "Fast Bowling", recommendedJersey: "India", recommendedFormat: "Test", recommendedPromptPreset: "Match Winner", recommendedQualityProfile: "High", recommendedCreativeStrategy: "Sports Broadcast", icon: "🔴" }),
  scene({ id: "century-celebration", sceneName: "Century Celebration", description: "Batter raising bat and helmet after a Test century with classic crowd applause.", category: "Test Cricket", difficulty: "Intermediate", popularity: "Classic", recommendedFor: ["Batsman", "Captain"], tags: ["Batsman", "Celebration", "Hero"], recommendedCamera: "Telephoto Lens", recommendedLighting: "Golden Hour", recommendedStadium: "The Oval", recommendedPose: "Celebration", recommendedJersey: "India", recommendedFormat: "Test", recommendedPromptPreset: "Match Winner", recommendedQualityProfile: "Ultra", recommendedCreativeStrategy: "Sports Magazine", icon: "💯" }),
  scene({ id: "captain-strategy", sceneName: "Captain Strategy", description: "Captain setting fields in whites with tactical body language and deep cricket atmosphere.", category: "Test Cricket", difficulty: "Intermediate", popularity: "Classic", recommendedFor: ["Captain"], tags: ["Captain", "Portrait", "Day Match"], recommendedCamera: "Broadcast Camera", recommendedLighting: "Morning", recommendedStadium: "Lord's", recommendedPose: "Walking into Stadium", recommendedJersey: "India", recommendedFormat: "Test", recommendedPromptPreset: "Legendary Captain", recommendedQualityProfile: "High", recommendedCreativeStrategy: "Sports Documentary", icon: "♟️" }),
  scene({ id: "tea-break-portrait", sceneName: "Tea Break Portrait", description: "Quiet Test match portrait near pavilion during interval with timeless cricket mood.", category: "Test Cricket", difficulty: "Easy", popularity: "Classic", recommendedFor: ["Batsman", "Captain", "Coach"], tags: ["Portrait", "Captain"], recommendedCamera: "Close-up Portrait", recommendedLighting: "Cloudy", recommendedStadium: "Lord's", recommendedPose: "Press Conference", recommendedJersey: "India", recommendedFormat: "Test", recommendedPromptPreset: "Press Conference", recommendedQualityProfile: "High", recommendedCreativeStrategy: "Player Portrait", icon: "☕" }),

  // ODI
  scene({ id: "opening-partnership", sceneName: "Opening Partnership", description: "Fresh ODI opening stance with new ball, bright field and confident batting energy.", category: "ODI", difficulty: "Intermediate", popularity: "Popular", recommendedFor: ["Batsman"], tags: ["Batsman", "Day Match", "Action"], recommendedCamera: "Broadcast Camera", recommendedLighting: "Afternoon", recommendedStadium: "Wankhede Stadium", recommendedPose: "Straight Drive", recommendedJersey: "India", recommendedFormat: "ODI", recommendedPromptPreset: "Match Winner", recommendedQualityProfile: "High", recommendedCreativeStrategy: "Sports Broadcast", icon: "🤝" }),
  scene({ id: "middle-overs", sceneName: "Middle Overs", description: "Tactical ODI middle overs scene with rotation, fielders and controlled batting rhythm.", category: "ODI", difficulty: "Intermediate", popularity: "Classic", recommendedFor: ["Batsman", "All-rounder", "Captain"], tags: ["Action", "Batsman"], recommendedCamera: "Broadcast Camera", recommendedLighting: "Afternoon", recommendedStadium: "Eden Gardens", recommendedPose: "Cover Drive", recommendedJersey: "India", recommendedFormat: "ODI", recommendedPromptPreset: "Training Session", recommendedQualityProfile: "Standard", recommendedCreativeStrategy: "Sports Broadcast", icon: "🧠" }),
  scene({ id: "death-overs", sceneName: "Death Overs", description: "High-pressure ODI death overs with yorker, crowd tension and dramatic lights.", category: "ODI", difficulty: "Pro", popularity: "Trending", recommendedFor: ["Bowler", "All-rounder"], tags: ["Bowler", "Action", "Night Match"], recommendedCamera: "Action Camera", recommendedLighting: "Floodlights", recommendedStadium: "Narendra Modi Stadium", recommendedPose: "Fast Bowling", recommendedJersey: "India", recommendedFormat: "ODI", recommendedPromptPreset: "Match Winner", recommendedQualityProfile: "Ultra", recommendedCreativeStrategy: "Sports Broadcast", icon: "🎯" }),
  scene({ id: "winning-six", sceneName: "Winning Six", description: "Last-over six with bat follow-through, ball trajectory and stadium explosion.", category: "ODI", difficulty: "Advanced", popularity: "Trending", recommendedFor: ["Batsman", "All-rounder"], tags: ["Batsman", "Action", "Celebration"], recommendedCamera: "Wide Stadium", recommendedLighting: "Floodlights", recommendedStadium: "Wankhede Stadium", recommendedPose: "Pull Shot", recommendedJersey: "India", recommendedFormat: "ODI", recommendedPromptPreset: "Match Winner", recommendedQualityProfile: "Ultra", recommendedCreativeStrategy: "Sports Broadcast", icon: "6️⃣" }),

  // T20
  scene({ id: "powerplay-attack", sceneName: "Powerplay Attack", description: "Explosive T20 powerplay batting with field inside circle and aggressive shot-making.", category: "T20", difficulty: "Advanced", popularity: "Popular", recommendedFor: ["Batsman", "All-rounder"], tags: ["Action", "Batsman", "Hero"], recommendedCamera: "Action Camera", recommendedLighting: "Afternoon", recommendedStadium: "M Chinnaswamy Stadium", recommendedPose: "Cover Drive", recommendedJersey: "India", recommendedFormat: "T20", recommendedPromptPreset: "Epic IPL", recommendedQualityProfile: "High", recommendedCreativeStrategy: "Sports Broadcast", icon: "🚀" }),
  scene({ id: "super-over", sceneName: "Super Over", description: "Ultimate T20 pressure scene under floodlights with dramatic stadium tension.", category: "T20", difficulty: "Pro", popularity: "Trending", recommendedFor: ["Batsman", "Bowler", "Captain"], tags: ["Action", "Night Match", "Hero"], recommendedCamera: "Telephoto Lens", recommendedLighting: "Floodlights", recommendedStadium: "Eden Gardens", recommendedPose: "Straight Drive", recommendedJersey: "India", recommendedFormat: "T20", recommendedPromptPreset: "Match Winner", recommendedQualityProfile: "Ultra", recommendedCreativeStrategy: "Sports Broadcast", icon: "🔥" }),
  scene({ id: "last-ball-finish", sceneName: "Last Ball Finish", description: "One-ball climax with cinematic tension, athletic focus and crowd anticipation.", category: "T20", difficulty: "Pro", popularity: "Trending", recommendedFor: ["Batsman", "Bowler"], tags: ["Action", "Hero", "Night Match"], recommendedCamera: "Slow Motion Style", recommendedLighting: "Floodlights", recommendedStadium: "Narendra Modi Stadium", recommendedPose: "Pull Shot", recommendedJersey: "India", recommendedFormat: "T20", recommendedPromptPreset: "Match Winner", recommendedQualityProfile: "Ultra", recommendedCreativeStrategy: "Movie Poster", icon: "⏱️" }),
  scene({ id: "fireworks-celebration", sceneName: "Fireworks Celebration", description: "T20 victory with fireworks, crowd, franchise colors and stadium celebration energy.", category: "T20", difficulty: "Advanced", popularity: "Trending", recommendedFor: ["Captain", "All-rounder", "Batsman"], tags: ["Celebration", "Night Match", "Poster"], recommendedCamera: "Wide Stadium", recommendedLighting: "Floodlights", recommendedStadium: "M Chinnaswamy Stadium", recommendedPose: "Celebration", recommendedJersey: "RCB", recommendedFormat: "T20", recommendedPromptPreset: "Victory Celebration", recommendedQualityProfile: "Ultra", recommendedCreativeStrategy: "Victory Celebration", icon: "🎆" }),

  // Training
  scene({ id: "gym-workout", sceneName: "Gym Workout", description: "Athlete strength session with professional cricket fitness environment and focused mood.", category: "Training", difficulty: "Easy", popularity: "Rising", recommendedFor: ["All-rounder", "Batsman", "Bowler"], tags: ["Training", "Portrait"], recommendedCamera: "Close-up Portrait", recommendedLighting: "Cloudy", recommendedStadium: "Wankhede Stadium", recommendedPose: "Practice Nets", recommendedJersey: "India", recommendedFormat: "International", recommendedPromptPreset: "Training Session", recommendedQualityProfile: "High", recommendedCreativeStrategy: "Training Session", icon: "🏋️" }),
  scene({ id: "fitness-training", sceneName: "Fitness Training", description: "Outdoor cricket fitness drills with cones, coaches and professional training kit.", category: "Training", difficulty: "Easy", popularity: "Popular", recommendedFor: ["All-rounder", "Coach"], tags: ["Training", "Day Match"], recommendedCamera: "Ground Level", recommendedLighting: "Morning", recommendedStadium: "M Chinnaswamy Stadium", recommendedPose: "Practice Nets", recommendedJersey: "India", recommendedFormat: "International", recommendedPromptPreset: "Training Session", recommendedQualityProfile: "Standard", recommendedCreativeStrategy: "Training Session", icon: "💪" }),
  scene({ id: "running-drills", sceneName: "Running Drills", description: "Speed and agility cricket drill with motion, training cones and stadium practice ground.", category: "Training", difficulty: "Intermediate", popularity: "Rising", recommendedFor: ["All-rounder", "Bowler"], tags: ["Training", "Action"], recommendedCamera: "Action Camera", recommendedLighting: "Morning", recommendedStadium: "Eden Gardens", recommendedPose: "Walking into Stadium", recommendedJersey: "India", recommendedFormat: "International", recommendedPromptPreset: "Training Session", recommendedQualityProfile: "Standard", recommendedCreativeStrategy: "Training Session", icon: "🏃" }),
  scene({ id: "throwing-practice", sceneName: "Throwing Practice", description: "Fielding throw drill with realistic ball release, coach attention and training field.", category: "Training", difficulty: "Intermediate", popularity: "Classic", recommendedFor: ["All-rounder", "Wicket Keeper"], tags: ["Training", "Action", "Wicket Keeper"], recommendedCamera: "Action Camera", recommendedLighting: "Afternoon", recommendedStadium: "The Oval", recommendedPose: "Celebration", recommendedJersey: "India", recommendedFormat: "International", recommendedPromptPreset: "Training Session", recommendedQualityProfile: "Standard", recommendedCreativeStrategy: "Training Session", icon: "🎯" }),
  scene({ id: "net-practice", sceneName: "Net Practice", description: "Focused net practice scene with bat, ball machine, coach and clean training composition.", category: "Training", difficulty: "Easy", popularity: "Popular", recommendedFor: ["Batsman", "Bowler", "Coach"], tags: ["Training", "Batsman", "Bowler"], recommendedCamera: "Ground Level", recommendedLighting: "Afternoon", recommendedStadium: "M Chinnaswamy Stadium", recommendedPose: "Practice Nets", recommendedJersey: "RCB", recommendedFormat: "IPL", recommendedPromptPreset: "Training Session", recommendedQualityProfile: "High", recommendedCreativeStrategy: "Net Practice", icon: "🥅" }),
  scene({ id: "batting-practice", sceneName: "Batting Practice", description: "Technical batting drill with controlled shot, nets and coach observation.", category: "Training", difficulty: "Easy", popularity: "Classic", recommendedFor: ["Batsman"], tags: ["Training", "Batsman"], recommendedCamera: "Telephoto Lens", recommendedLighting: "Afternoon", recommendedStadium: "Wankhede Stadium", recommendedPose: "Straight Drive", recommendedJersey: "India", recommendedFormat: "International", recommendedPromptPreset: "Training Session", recommendedQualityProfile: "High", recommendedCreativeStrategy: "Net Practice", icon: "🏏" }),
  scene({ id: "bowling-practice", sceneName: "Bowling Practice", description: "Bowler practicing line and length in nets with professional training realism.", category: "Training", difficulty: "Intermediate", popularity: "Classic", recommendedFor: ["Bowler"], tags: ["Training", "Bowler", "Action"], recommendedCamera: "Action Camera", recommendedLighting: "Morning", recommendedStadium: "Eden Gardens", recommendedPose: "Fast Bowling", recommendedJersey: "India", recommendedFormat: "International", recommendedPromptPreset: "Training Session", recommendedQualityProfile: "High", recommendedCreativeStrategy: "Net Practice", icon: "⚾" }),
];

const sceneCache = new Map<string, SceneTemplate>();

export class SceneLibrary {
  getAll() {
    return scenes;
  }

  getById(id: string) {
    if (sceneCache.has(id)) return sceneCache.get(id) ?? null;
    const found = scenes.find((sceneTemplate) => sceneTemplate.id === id) ?? null;
    if (found) sceneCache.set(id, found);
    return found;
  }
}

export const sceneLibrary = new SceneLibrary();
